# Usa Node.js 18 (LTS)
FROM node:18-alpine

# Diretório de trabalho
WORKDIR /usr/src/app

# Copia package.json e instala dependências
COPY package*.json ./
RUN npm install

# Copia o resto dos arquivos
COPY . .

# Expõe a porta 5000 (ou a que você usa)
EXPOSE 5000

# Comando para iniciar a aplicação
CMD ["node", "src/index.js"]